application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/studs
        username: s335160
        password: wIoLzrRkt4v2zo01
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    kafka:
        bootstrap-servers: localhost:29091
        producer:
            transaction-id-prefix: tx-